Updated Readme
pcdslab/ProteoRift pull request #7
Opened 2024-09-30 18:42 UTC by bilals08

2024-10-01 19:34 UTC, Prof-S requested changes

2024-10-01 19:34 UTC, Prof-S commented on toe_image.png
We cannot put in the graph like this. 
Use something like if you have a 2 GB of database and 100k spectra then it will take this much hours. Use the numbers from the graph though

2024-10-01 19:34 UTC, Prof-S commented on README.md
> +## Uncertainty Analysis
Uncertainity analysis can come before the "Retrain the model".

2024-10-01 19:34 UTC, Prof-S commented on README.md
>  ```
Expected output is still missing.

2024-10-02 17:43 UTC, bilals08 commented on toe_image.png
I have fixed the changes.

2024-10-02 18:46 UTC, Prof-S approved these changes

2024-10-02 18:46 UTC, merged